### ISSUE TITLE
How to do a single denoising prediction for a given set of joint (x,y) values?

### ISSUE THREAD

**Issue by theneuronprogrammer** [cure-lab/DeciWatch#10]
i/p - [(x1, y1), (x2, y2), ...... , (xn, yn)]

I want output as - 

o/p -   [(x1_corrected, y1_corrected), (x2_corrected, y2_corrected), ...... , (xn_corrected, yn_corrected)]

**Comment by juxuan27** [comment]
Hi, @theneuronprogrammer ! Thank you for your focus!
Do you mean how to denoise the predicted poses without sampling? If so, simply changing the sample interval to 1 would work. We have also provided corresponding checkpoints on google drive and baidu disk.
