### ISSUE TITLE
论文后续有何改进的方向？

### ISSUE THREAD

**Issue by haofeng0705** [cure-lab/DeciWatch#13]
我有一个想法：可以先进行每帧的分析，选择动作幅度较大的帧作为关键帧，这种能否进一步优化网络？

**Comment by juxuan27** [comment]
Hi, @Elliot-hao ! Thank you for your focus!
It's a good idea and worth trying. But I believe you need to consider the following points carefully: (1) How to choose keyframes? What is the criterion? What is a big movement range? (2) How to make sure computational efficiency while using all frames to select keyframes?
Some citations listed in our paper may help you, especially the ones following the pipeline of Fig.1(b). We welcome your discussion at any time and hope we could create more valuable work together.
