### ISSUE TITLE
Add a script for own video input in .mp4 etc. and/or webcam input

### ISSUE THREAD

**Issue by GKeppler** [cure-lab/DeciWatch#14]
First of all, thank you very much for your work. It is very nice to explore with the good documentation. I think the above mentioned scripts a re missing. It would be very nice to see those in the demo.py.

Greetings Gustav

**Comment by juxuan27** [comment]
Hi, @GKeppler ! Thank you for your focus!
At present, we have not provided the script for users' own video input and/or webcam input. However, DeciWatch is already implemented in (MMHuman3D)[https://github.com/open-mmlab/mmhuman3d] and you can check the performance of DeciWatch on any video there.
