### ISSUE TITLE
How to add custom data?

### ISSUE THREAD

**Issue by haofeng0705** [cure-lab/DeciWatch#15]
Thanks for your great work! 
For the human3.6M dataset, my goal is to change the backbone network fcn (to e.g. videopose 3d), how to get the .npz files like yours?
<img width="238" alt="image" src="https://user-images.githubusercontent.com/30925823/192470749-c0665283-2979-4620-99ae-487d1e456c72.png">

**Comment by juxuan27** [comment]
Hi, @Elliot-hao ! Thank you for your focus!
You can follow the instructions [here](https://github.com/cure-lab/DeciWatch/blob/main/doc/data.md) to add your own data.
