### ISSUE TITLE
数据处理的问题

### ISSUE THREAD

**Issue by haofeng0705** [cure-lab/DeciWatch#16]
您好，我想使用自定义human3.6M的 npz，您在readme 中写道需要使用 root-relative 的数据，但是对原文代码 debug 的时候，里面的数据并不是 root-relative 的
<img width="622" alt="image" src="https://user-images.githubusercontent.com/30925823/196157572-e7c13b21-3c07-469c-8530-dd1791f69e2c.png">
请问最后应该保持哪种格式？
![image](https://user-images.githubusercontent.com/30925823/196157706-d8b2cde9-6059-40e6-8d5b-01a4d462faf7.png)
这个图中上面的表示我已经处理好的 root-relative 的关节数据
下面则是您 npz 中的数据？感谢回答

**Comment by juxuan27** [comment]
Hi, @Elliot-hao ! Thank you for your focus.

In fact, the code to process npz data to root-relative is [here](https://github.com/cure-lab/DeciWatch/blob/5afe2d67005441e2785a8d374d31a91f046a0da6/lib/dataset/h36m_dataset.py#L195). You do not need to make the data in npz file to be root-relative.
