### ISSUE TITLE
Questions about network structure

### ISSUE THREAD

**Issue by haofeng0705** [cure-lab/DeciWatch#20]
According to the setting of the paper, for 3dhpe, we can only input 3d poses, and output smooth 3D poses through DeciWatch network. Can we directly input 2D poses, and use the network to lifting the dimension and reduce the noise? Looking forward to your reply:）

**Comment by ailingzengzzz** [comment]
Hi @Elliot-hao ,

This is an interesting question. You can try to use the input of 2D poses and simply modify the output dimension as 3D poses with 3D pose GT supervision on your data.

**Comment by haofeng0705** [comment]
Hello, @ailingzengzzz. I tried to follow your method to create a 2D dataset as input, but I'm not quite sure how to implement the modification of the output dimension that you mentioned. Where should the process of dimensionality uplifting be reflected?
