### ISSUE TITLE
Inference on custom videos and multi people tracking 

### ISSUE THREAD

**Issue by CloudedLeopard17** [cure-lab/DeciWatch#5]
Hi, Thanks for your great work. I want to do inference on my custom video, how to do it? Also, does it supports multi people tracking?

**Comment by ailingzengzzz** [comment]
Hi, @CloudedLeopard17,
As we discussed in the Quick Demo, we only provide demo visualization based on offline processed detected poses of specific datasets(e.g. AIST++, Human3.6M, 3DPW, and Sub-JHMDB). To visualize on arbitrary given video, please refer to the [inference/demo](https://github.com/open-mmlab/mmhuman3d/blob/main/docs/getting_started.md) of [MMHuman3D](https://github.com/open-mmlab/mmhuman3d). 
This version does not support multiple person tracking. You may simply use top-down pipelines to first detect and recognize the same person, then use DeciWatch for each person.

**Comment by CloudedLeopard17** [comment]
Thanks @ailingzengzzz
