### ISSUE TITLE
Bad deciwatch output

### ISSUE THREAD

**Issue by CloudedLeopard17** [cure-lab/DeciWatch#7]
Hi, I have 3d joints data of person in inches, I converted this data to meters and trying to run deciwatch. All results are good except the deciwatch. I also tried to normalized data wrt the hip mid-point but the results look the same. Any Idea what I am doing wrong ?
![result](https://user-images.githubusercontent.com/33505589/181508244-26e839d3-0793-412e-8e82-416efd4c8d17.png)

**Comment by ailingzengzzz** [comment]
Hi @CloudedLeopard17,

Thanks for your kind feedback!
Do you train DeciWatch on your own data or simply use the pre-trained models? Could you please show the values in a frame (shape is [K, 3]) for us?  I also noticed that the Accel of DeciWatch and Linear interpolation is the same and the values are quite large, which is strange.

**Comment by CloudedLeopard17** [comment]
Hi, @ailingzengzzz I am using the pre-trained model. 

Here is the joints_3d data for a random frame.

```
array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 5.09130300e-02,  8.58469200e-03, -9.17760420e-03],
        [ 4.68896700e-02,  2.73664680e-02, -3.79798555e-01],
        [ 4.18223700e-02,  8.38200000e-04, -7.62541325e-01],
        [-5.09130300e-02, -8.58469200e-03,  9.17760420e-03],
        [-5.59650900e-02,  4.28198280e-02, -3.86852922e-01],
        [-5.96150700e-02, -1.04615742e-01, -6.38541156e-01],
        [-1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
        [ 2.95617900e-02,  2.56767330e-02,  4.66939541e-01],
        [-1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
        [ 4.24319700e-02,  1.09430820e-01,  6.43616518e-01],
        [ 1.09762290e-01,  5.70882780e-02,  4.42746536e-01],
        [ 1.53150570e-01,  8.95471920e-02,  3.05216128e-01],
        [ 1.97369430e-01,  1.10387892e-01,  7.72459212e-02],
        [-5.06387100e-02, -5.73481200e-03,  4.91132546e-01],
        [-1.07765850e-01, -5.04108720e-02,  3.47317466e-01],
        [-8.47610700e-02, -2.58043680e-02,  1.14915772e-01]]])
```

I am not using spine and head. Also, does the first **hip** point means the midpoint of **lhip** and **rhip** ?

**Comment by ailingzengzzz** [comment]
Which pose estimator and dataset do you use?
For DeciWatch, we recommend training it for each pose estimator (e.g., SPIN) on each dataset (e.g., 3DPW) to ensure performance. Thus, do you use the corresponding pre-trained model?

Yes, the first hip is the root keypoint (midpoint of lhip and rhip).

**Comment by CloudedLeopard17** [comment]
I didn't train the model. Using pre-trained 3DPW pare model. The 3d joints were calculated using hrnet model.

**Comment by ailingzengzzz** [comment]
Hi @CloudedLeopard17,

We recommend training the DeciWatch model for different backbones and datasets since different data has their bias.
