### ISSUE TITLE
How to use multiple GPUs to accelerate training?

### ISSUE THREAD

**Issue by haofeng0705** [cure-lab/DeciWatch#9]
Tried to add following code:
model = nn.DataParallel(model)
model = model.cuda()
not working :(
![image](https://user-images.githubusercontent.com/30925823/183553856-7471f204-b1a6-4303-a02f-529ad25fb029.png)

**Comment by juxuan27** [comment]
Hi, @Elliot-hao ! Thank you for your focus!
Our code does not support multiple GPU training and testing. We are welcome for PR if you can help us add it!
